#!/bin/sh

sbatch -p dgxh100 -t 12:00:00 --mem-per-cpu 32G --cpus-per-task 1 --output=output.log --wrap="time python main.py" &&
watch -n 1 squeue -u vlad_adrian.ulmeanu

# cat timp a luat rularea jobului:
# sacct -j <myid> --format=Elapsed

# cancel job direct:
# scancel $(squeue -u vlad_adrian.ulmeanu | sed -n '2 p' | sed 's/ /\n/g' | sed -n '13 p')
